### ISSUE TITLE
Positioning bug with Vibrancy Enabled

### ISSUE THREAD

**Issue by gbrian97** [UsrLightmann/TextTime#2]
The positioning is off when vibrancy is enabled. I’m using IPhone 11 13.5 uncover.

**Comment by L1ghtmann** [comment]
Hmm, that is so weird. 

I just turned it on to check and it does indeed bug.

**EDIT**: Does _not_ occur on older versions as I had initially stated. 

Will look into it. Thanks for letting me know!

**Comment by gbrian97** [comment]
Glad I can bring it to your attention to help :)

**Comment by L1ghtmann** [comment]
Fixed in v1.0.0.2
